// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package dbsqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertTransaction = `-- name: InsertTransaction :batchexec
INSERT INTO transactions (block_num, tx_num, tx_id, validation_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (block_num, tx_num) DO UPDATE SET tx_id = EXCLUDED.tx_id
`

type InsertTransactionBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTransactionParams struct {
	BlockNum       int64  `json:"block_num"`
	TxNum          int64  `json:"tx_num"`
	TxID           []byte `json:"tx_id"`
	ValidationCode int64  `json:"validation_code"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg []InsertTransactionParams) *InsertTransactionBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.TxID,
			a.ValidationCode,
		}
		batch.Queue(insertTransaction, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTransactionBatchResults{br, len(arg), false}
}

func (b *InsertTransactionBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTransactionBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTxEndorsement = `-- name: InsertTxEndorsement :batchexec
INSERT INTO tx_endorsements (block_num, tx_num, ns_id, endorsement, msp_id, identity)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTxEndorsementBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTxEndorsementParams struct {
	BlockNum    int64       `json:"block_num"`
	TxNum       int64       `json:"tx_num"`
	NsID        string      `json:"ns_id"`
	Endorsement []byte      `json:"endorsement"`
	MspID       pgtype.Text `json:"msp_id"`
	Identity    []byte      `json:"identity"`
}

func (q *Queries) InsertTxEndorsement(ctx context.Context, arg []InsertTxEndorsementParams) *InsertTxEndorsementBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.Endorsement,
			a.MspID,
			a.Identity,
		}
		batch.Queue(insertTxEndorsement, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTxEndorsementBatchResults{br, len(arg), false}
}

func (b *InsertTxEndorsementBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTxEndorsementBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTxNamespace = `-- name: InsertTxNamespace :batchexec
INSERT INTO tx_namespaces (block_num, tx_num, ns_id, ns_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (block_num, tx_num, ns_id) DO UPDATE SET ns_version = EXCLUDED.ns_version
`

type InsertTxNamespaceBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTxNamespaceParams struct {
	BlockNum  int64  `json:"block_num"`
	TxNum     int64  `json:"tx_num"`
	NsID      string `json:"ns_id"`
	NsVersion int64  `json:"ns_version"`
}

func (q *Queries) InsertTxNamespace(ctx context.Context, arg []InsertTxNamespaceParams) *InsertTxNamespaceBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.NsVersion,
		}
		batch.Queue(insertTxNamespace, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTxNamespaceBatchResults{br, len(arg), false}
}

func (b *InsertTxNamespaceBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTxNamespaceBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTxRead = `-- name: InsertTxRead :batchexec
INSERT INTO tx_reads (block_num, tx_num, ns_id, key, version, is_read_write)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTxReadBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTxReadParams struct {
	BlockNum    int64       `json:"block_num"`
	TxNum       int64       `json:"tx_num"`
	NsID        string      `json:"ns_id"`
	Key         []byte      `json:"key"`
	Version     pgtype.Int8 `json:"version"`
	IsReadWrite bool        `json:"is_read_write"`
}

func (q *Queries) InsertTxRead(ctx context.Context, arg []InsertTxReadParams) *InsertTxReadBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.Key,
			a.Version,
			a.IsReadWrite,
		}
		batch.Queue(insertTxRead, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTxReadBatchResults{br, len(arg), false}
}

func (b *InsertTxReadBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTxReadBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTxWrite = `-- name: InsertTxWrite :batchexec
INSERT INTO tx_writes (block_num, tx_num, ns_id, key, value, is_blind_write, read_version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTxWriteBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTxWriteParams struct {
	BlockNum     int64       `json:"block_num"`
	TxNum        int64       `json:"tx_num"`
	NsID         string      `json:"ns_id"`
	Key          []byte      `json:"key"`
	Value        []byte      `json:"value"`
	IsBlindWrite bool        `json:"is_blind_write"`
	ReadVersion  pgtype.Int8 `json:"read_version"`
}

func (q *Queries) InsertTxWrite(ctx context.Context, arg []InsertTxWriteParams) *InsertTxWriteBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.BlockNum,
			a.TxNum,
			a.NsID,
			a.Key,
			a.Value,
			a.IsBlindWrite,
			a.ReadVersion,
		}
		batch.Queue(insertTxWrite, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTxWriteBatchResults{br, len(arg), false}
}

func (b *InsertTxWriteBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTxWriteBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertNamespacePolicy = `-- name: UpsertNamespacePolicy :batchexec
INSERT INTO namespace_policies (namespace, version, policy)
VALUES ($1, $2, $3)
ON CONFLICT (namespace, version) DO UPDATE SET policy = EXCLUDED.policy
`

type UpsertNamespacePolicyBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertNamespacePolicyParams struct {
	Namespace string `json:"namespace"`
	Version   int64  `json:"version"`
	Policy    []byte `json:"policy"`
}

func (q *Queries) UpsertNamespacePolicy(ctx context.Context, arg []UpsertNamespacePolicyParams) *UpsertNamespacePolicyBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Namespace,
			a.Version,
			a.Policy,
		}
		batch.Queue(upsertNamespacePolicy, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertNamespacePolicyBatchResults{br, len(arg), false}
}

func (b *UpsertNamespacePolicyBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertNamespacePolicyBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
