// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: envelope_errors.sql

package dbsqlc

import (
	"context"
)

const getEnvelopeErrorsByBlock = `-- name: GetEnvelopeErrorsByBlock :many
SELECT block_num, tx_num, validation_code, raw_envelope, tx_id
FROM block_envelope_errors
WHERE block_num = $1
ORDER BY tx_num
`

func (q *Queries) GetEnvelopeErrorsByBlock(ctx context.Context, blockNum int64) ([]BlockEnvelopeError, error) {
	rows, err := q.db.Query(ctx, getEnvelopeErrorsByBlock, blockNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BlockEnvelopeError{}
	for rows.Next() {
		var i BlockEnvelopeError
		if err := rows.Scan(
			&i.BlockNum,
			&i.TxNum,
			&i.ValidationCode,
			&i.RawEnvelope,
			&i.TxID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
