// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	BlockNum     int64  `json:"block_num"`
	TxCount      int32  `json:"tx_count"`
	PreviousHash []byte `json:"previous_hash"`
	DataHash     []byte `json:"data_hash"`
}

type NamespacePolicy struct {
	Namespace string `json:"namespace"`
	Version   int64  `json:"version"`
	Policy    []byte `json:"policy"`
}

type Transaction struct {
	BlockNum       int64  `json:"block_num"`
	TxNum          int64  `json:"tx_num"`
	TxID           []byte `json:"tx_id"`
	ValidationCode int16  `json:"validation_code"`
}

type TxBlindWrite struct {
	BlockNum int64  `json:"block_num"`
	TxNum    int64  `json:"tx_num"`
	NsID     string `json:"ns_id"`
	Key      []byte `json:"key"`
	Value    []byte `json:"value"`
}

type TxEndorsement struct {
	BlockNum    int64       `json:"block_num"`
	TxNum       int64       `json:"tx_num"`
	NsID        string      `json:"ns_id"`
	Endorsement []byte      `json:"endorsement"`
	MspID       pgtype.Text `json:"msp_id"`
	Identity    []byte      `json:"identity"`
}

type TxNamespace struct {
	BlockNum  int64  `json:"block_num"`
	TxNum     int64  `json:"tx_num"`
	NsID      string `json:"ns_id"`
	NsVersion int64  `json:"ns_version"`
}

type TxReadWrite struct {
	BlockNum    int64       `json:"block_num"`
	TxNum       int64       `json:"tx_num"`
	NsID        string      `json:"ns_id"`
	Key         []byte      `json:"key"`
	ReadVersion pgtype.Int8 `json:"read_version"`
	Value       []byte      `json:"value"`
}

type TxReadsOnly struct {
	BlockNum int64       `json:"block_num"`
	TxNum    int64       `json:"tx_num"`
	NsID     string      `json:"ns_id"`
	Key      []byte      `json:"key"`
	Version  pgtype.Int8 `json:"version"`
}
