// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: namespace_policies.sql

package dbsqlc

import (
	"context"
)

const getNamespacePolicies = `-- name: GetNamespacePolicies :many
SELECT namespace, version, policy
FROM namespace_policies
WHERE namespace = $1
ORDER BY version DESC
`

func (q *Queries) GetNamespacePolicies(ctx context.Context, namespace string) ([]NamespacePolicy, error) {
	rows, err := q.db.Query(ctx, getNamespacePolicies, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NamespacePolicy{}
	for rows.Next() {
		var i NamespacePolicy
		if err := rows.Scan(&i.Namespace, &i.Version, &i.Policy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
