// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_endorsements.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEndorsementsByTx = `-- name: GetEndorsementsByTx :many
SELECT ns_id, endorsement, msp_id, identity
FROM tx_endorsements
WHERE block_num = $1 AND tx_num = $2
ORDER BY ns_id, endorsement
`

type GetEndorsementsByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
}

type GetEndorsementsByTxRow struct {
	NsID        string      `json:"ns_id"`
	Endorsement []byte      `json:"endorsement"`
	MspID       pgtype.Text `json:"msp_id"`
	Identity    []byte      `json:"identity"`
}

func (q *Queries) GetEndorsementsByTx(ctx context.Context, arg GetEndorsementsByTxParams) ([]GetEndorsementsByTxRow, error) {
	rows, err := q.db.Query(ctx, getEndorsementsByTx, arg.BlockNum, arg.TxNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEndorsementsByTxRow{}
	for rows.Next() {
		var i GetEndorsementsByTxRow
		if err := rows.Scan(
			&i.NsID,
			&i.Endorsement,
			&i.MspID,
			&i.Identity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
