// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_namespaces.sql

package dbsqlc

import (
	"context"
)

const getNamespacesByBlockTxRange = `-- name: GetNamespacesByBlockTxRange :many
SELECT tx_num, ns_id, ns_version
FROM tx_namespaces
WHERE block_num = $1 AND tx_num >= $2 AND tx_num < $3
ORDER BY tx_num, ns_id
`

type GetNamespacesByBlockTxRangeParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
	TxNum_2  int64 `json:"tx_num_2"`
}

type GetNamespacesByBlockTxRangeRow struct {
	TxNum     int64  `json:"tx_num"`
	NsID      string `json:"ns_id"`
	NsVersion int64  `json:"ns_version"`
}

func (q *Queries) GetNamespacesByBlockTxRange(ctx context.Context, arg GetNamespacesByBlockTxRangeParams) ([]GetNamespacesByBlockTxRangeRow, error) {
	rows, err := q.db.Query(ctx, getNamespacesByBlockTxRange, arg.BlockNum, arg.TxNum, arg.TxNum_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNamespacesByBlockTxRangeRow{}
	for rows.Next() {
		var i GetNamespacesByBlockTxRangeRow
		if err := rows.Scan(&i.TxNum, &i.NsID, &i.NsVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNamespacesByTx = `-- name: GetNamespacesByTx :many
SELECT ns_id, ns_version
FROM tx_namespaces
WHERE block_num = $1 AND tx_num = $2
ORDER BY ns_id
`

type GetNamespacesByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
}

type GetNamespacesByTxRow struct {
	NsID      string `json:"ns_id"`
	NsVersion int64  `json:"ns_version"`
}

func (q *Queries) GetNamespacesByTx(ctx context.Context, arg GetNamespacesByTxParams) ([]GetNamespacesByTxRow, error) {
	rows, err := q.db.Query(ctx, getNamespacesByTx, arg.BlockNum, arg.TxNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNamespacesByTxRow{}
	for rows.Next() {
		var i GetNamespacesByTxRow
		if err := rows.Scan(&i.NsID, &i.NsVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
