// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_reads.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReadsByTx = `-- name: GetReadsByTx :many
SELECT ns_id, key, version, is_read_write
FROM tx_reads
WHERE block_num = $1 AND tx_num = $2
ORDER BY ns_id, key
`

type GetReadsByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
}

type GetReadsByTxRow struct {
	NsID        string      `json:"ns_id"`
	Key         []byte      `json:"key"`
	Version     pgtype.Int8 `json:"version"`
	IsReadWrite bool        `json:"is_read_write"`
}

func (q *Queries) GetReadsByTx(ctx context.Context, arg GetReadsByTxParams) ([]GetReadsByTxRow, error) {
	rows, err := q.db.Query(ctx, getReadsByTx, arg.BlockNum, arg.TxNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReadsByTxRow{}
	for rows.Next() {
		var i GetReadsByTxRow
		if err := rows.Scan(
			&i.NsID,
			&i.Key,
			&i.Version,
			&i.IsReadWrite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
