// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_reads_only.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReadsOnlyByTx = `-- name: GetReadsOnlyByTx :many
SELECT ns_id, key, version
FROM tx_reads_only
WHERE block_num = $1 AND tx_num = $2
ORDER BY ns_id, key
`

type GetReadsOnlyByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
}

type GetReadsOnlyByTxRow struct {
	NsID    string      `json:"ns_id"`
	Key     []byte      `json:"key"`
	Version pgtype.Int8 `json:"version"`
}

func (q *Queries) GetReadsOnlyByTx(ctx context.Context, arg GetReadsOnlyByTxParams) ([]GetReadsOnlyByTxRow, error) {
	rows, err := q.db.Query(ctx, getReadsOnlyByTx, arg.BlockNum, arg.TxNum)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReadsOnlyByTxRow{}
	for rows.Next() {
		var i GetReadsOnlyByTxRow
		if err := rows.Scan(&i.NsID, &i.Key, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
