// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tx_writes.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWritesByTx = `-- name: GetWritesByTx :many
SELECT ns_id, key, value, is_blind_write, read_version
FROM tx_writes
WHERE block_num = $1 AND tx_num = $2
ORDER BY ns_id, key
LIMIT $3 OFFSET $4
`

type GetWritesByTxParams struct {
	BlockNum int64 `json:"block_num"`
	TxNum    int64 `json:"tx_num"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type GetWritesByTxRow struct {
	NsID         string      `json:"ns_id"`
	Key          []byte      `json:"key"`
	Value        []byte      `json:"value"`
	IsBlindWrite bool        `json:"is_blind_write"`
	ReadVersion  pgtype.Int8 `json:"read_version"`
}

func (q *Queries) GetWritesByTx(ctx context.Context, arg GetWritesByTxParams) ([]GetWritesByTxRow, error) {
	rows, err := q.db.Query(ctx, getWritesByTx,
		arg.BlockNum,
		arg.TxNum,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWritesByTxRow{}
	for rows.Next() {
		var i GetWritesByTxRow
		if err := rows.Scan(
			&i.NsID,
			&i.Key,
			&i.Value,
			&i.IsBlindWrite,
			&i.ReadVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
